name: Build Rust with OpenSSL (MSVC)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable-msvc
    
    - name: Setup OpenSSL
      shell: pwsh
      run: |
        ./setup-rust-openssl.ps1
      
    - name: Build with Cargo
      run: |
        cargo build --verbose
      env:
        OPENSSL_DIR: C:\OpenSSL
        OPENSSL_LIB_DIR: C:\OpenSSL\lib
        OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
    
    - name: Run tests
      run: |
        cargo test --verbose
      env:
        OPENSSL_DIR: C:\OpenSSL
        OPENSSL_LIB_DIR: C:\OpenSSL\lib
        OPENSSL_INCLUDE_DIR: C:\OpenSSL\include